[profile.ci.fuzz]
runs = 10_000

[profile.default]
# Skip gas tests on CI
# Run them in development manually by commenting `no_match_path` line and running "forge test --mc ETHTransferTest -vvvv"
# don't forget to turn on the optimizer :)
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports=[
    "PufferPool",
    "EigenPodProxy",
    "PufferAVSRegistry"
]
auto_detect_solc = false
cbor_metadata = false
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
solc = "0.8.20"
evm_version = "shanghai"

[fmt]
line_length = 120
int_types = "long"
tab_width = 4
quote_style = "double"
bracket_spacing = true

[rpc_endpoints]
# mainnet="https://eth-mainnet-public.unifra.io"
# mainnet="https://eth.llamarpc.com"
# goerli="https://ethereum-goerli-archive.allthatnode.com"
goerli="${GOERLI_RPC_URL}"

[invariant]
# fail_on_revert=true
depth = 20
# runs = 10000