[profile.ci.fuzz]
runs = 7_000

[profile.default]
# Skip gas tests on CI
# Run them in development manually by commenting `no_match_path` line and running "forge test --mc ETHTransferTest -vvvv"
# don't forget to turn on the optimizer :)
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports=[
    "PufferProtocol",
    "GuardianModule",
    "RestakingOperator",
    "EnclaveVerifier",
    "PufferModuleManager",
    "PufferModule",
    "ValidatorTicket"
]
auto_detect_solc = false
cbor_metadata = false
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
seed = "0x1337" # uncomment / change when debugging fuzz tests
# via_ir = true
solc = "0.8.24"
evm_version = "cancun"

[fmt]
line_length = 120
int_types = "long"
tab_width = 4
quote_style = "double"
bracket_spacing = true

[rpc_endpoints]
mainnet="${ETH_RPC_URL}"
goerli="${GOERLI_RPC_URL}"
holesky="${HOLESKY_RPC_URL}"

[invariant]
fail_on_revert=false
depth = 110
runs = 100