[profile.ci.fuzz]
runs = 10_000

[profile.default]
# Skip gas tests on CI
# Run them in development manually by commenting `no_match_path` line and running "forge test --mc ETHTransferTest -vvvv"
# don't forget to turn on the optimizer :)
no_match_path = "test/gas-tests/*.sol"

optimizer = false
optimizer_runs = 10_000
solc = "0.8.20"
evm_version = "shanghai"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet="https://eth-mainnet-public.unifra.io"