name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run tests
        run: forge test -vvvv

      # - name: Check gas snapshots
      #   run: forge snapshot 
  
  slither: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crytic/slither-action@v0.3.0
        with:
          node-version: 18.15

